### ISSUE TITLE
Remove/filter unwanted properties from body

### ISSUE THREAD

**Issue by indymaat** [akumbhani66/mongoose-morgan-body#1]
I have mongoose-morgan-body set up using the following configuration, all is fine and dandy:
```app.use(
  morgan(
      {
          collection: "log_http",
          connectionString: process.env.MONGODB_LOG_URI,
      },
      {
          filterParameters: ["password"],
          skip: () => {
              return (
                  process.env.NODE_ENV === "test" ||
                  (process.env.NODE_ENV === "production" &&
                      res.statusCode < 300)
              );
          },

      },
      ":method === :url === :status === :response-time ms === :res[content-length] === :body === :resBody === :req[content-length]"
  )
```

If someone now logs in using a wrong name or password, the full request body with that username and password is logged. Is it possible to let mongoose-morgan-body filter out some reserved properties such as a password? I have seen that [morgan-body](https://github.com/sirrodgepodge/morgan-body) has a [filterParameter option](https://github.com/sirrodgepodge/morgan-body#morganbodyexpress-instance-options-object) but i believe this package is not dependant on morgan-body. 

So the following log:
```
{
    "_id" : ObjectId("61969466c936ba55741210ed"),
    "date" : ISODate("2021-11-18T17:59:02.885Z"),
    "log" : "POST === /login === 400 === 5.227 ms === 276 === {\"username\":\"foo\",\"password\":\"bar\"} === - === 29",
    "method" : "POST",
    "endpoint" : "/login",
    "responseCode" : "400",
    "responseTime" : 5.227,
    "bodySize" : "276",
    "requestBody" : {
        "username" : "foo",
        "password" : "bar"
    },
    "responseBody" : " - ",
    "__v" : 0
}
```
Should actually result in removing/replacing the value like below (or maybe even omit the field "password"):

```
{
    "_id" : ObjectId("61969466c936ba55741210ed"),
    "date" : ISODate("2021-11-18T17:59:02.885Z"),
    "log" : "POST === /login === 400 === 5.227 ms === 276 === {\"username\":\"foo\",\"password\":\"[filtered]\"} === - === 29",
    "method" : "POST",
    "endpoint" : "/login",
    "responseCode" : "400",
    "responseTime" : 5.227,
    "bodySize" : "276",
    "requestBody" : {
        "username" : "foo",
        "password" : "[filtered]"
    },
    "responseBody" : " - ",
    "__v" : 0
}
```

Is it possible to filter out certain parameters when logging?

**Comment by akumbhani66** [comment]
@indymaat , This is interesting. I'll find some workaround for it.

**Comment by indymaat** [comment]
@akumbhani66 any news on this topic?

**Comment by akumbhani66** [comment]
@indymaat , Apologies for the delay. Was occupied a lot. For now, i have simply removed the password from the body. But the condition is key name must be `password`.

Please refer the changes [here](https://github.com/akumbhani66/mongoose-morgan-body/commit/9ac1614853562b3c29514881c66ffafe6262007a). Feel free to add more suggestions. 

In case its fullfill your requirements, Close the issue.

**Comment by akumbhani66** [comment]
Also, i haven't got a chance to test it out thoroughly.
